// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ldzqhnzppsklsgbojkkw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxkenFobnpwcHNrbHNnYm9qa2t3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI0NzQ1MTAsImV4cCI6MjA0ODA1MDUxMH0.kK0I7rVO_e3Y_Whj65ctiaRo6WuMyudC8H4bD7vbcjg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);